CREATE TABLE IF NOT EXISTS score_exams (
  id VARCHAR(64) PRIMARY KEY,
  class_id VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  type VARCHAR(64) NOT NULL,
  exam_date VARCHAR(32) NOT NULL,
  subject_coverage VARCHAR(255) NOT NULL,
  subjects JSON NOT NULL,
  import_status VARCHAR(32) NOT NULL,
  file_name VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_score_exams_class FOREIGN KEY (class_id) REFERENCES classroom_classes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS score_rows (
  id VARCHAR(64) PRIMARY KEY,
  exam_id VARCHAR(64) NOT NULL,
  student_id VARCHAR(64) NOT NULL,
  student_name VARCHAR(64) NOT NULL,
  chinese VARCHAR(16) NOT NULL,
  math VARCHAR(16) NOT NULL,
  english VARCHAR(16) NOT NULL,
  elective_label VARCHAR(64) NOT NULL,
  elective_score VARCHAR(16) NOT NULL,
  total VARCHAR(16) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_score_rows_exam FOREIGN KEY (exam_id) REFERENCES score_exams(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS score_import_issues (
  id VARCHAR(64) PRIMARY KEY,
  exam_id VARCHAR(64) NOT NULL,
  row_no VARCHAR(32) NOT NULL,
  student VARCHAR(128) NOT NULL,
  issue VARCHAR(255) NOT NULL,
  suggestion VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_score_import_issues_exam FOREIGN KEY (exam_id) REFERENCES score_exams(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
